name: Build and Test

on:
  push:
    # branches:
    #   - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci
        env:
          POYRO_API_KEY: ${{ secrets.POYRO_API_KEY }}
